env:
  browser: true
  es6: true
extends: 'eslint:recommended'
rules:
  global-require: "off"
  no-undef: "off"
  no-console: "off"
  no-unused-vars: "off"
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
